# This file should be included in .gitignore to not store sensitive data in version control
import os
SECRET_KEY = os.urandom(32)

# Grabs the folder where the script runs.
basedir = os.path.abspath(os.path.dirname(__file__))

database_setup = {
   "database_name" : "casting",
   "user_name" : "postgres", # Default postgres user name
   "password" : "postgres", # If applicable. If no password, just type in None
   "port" : "localhost:5432" # Default postgres port
}

auth0_config = {
    "AUTH0_DOMAIN" : "fsnds.eu.auth0.com", # The auth0 domain prefix
    "ALGORITHMS" : ["RS256"],
    "API_AUDIENCE" : "Casting", # The audience set for the auth0 app
    "clientId": 'reIq7tebc917ZSQZTmiKcHTbY4I8OTMf', # The client id generated for the auth0 app,
    "callbackURL": 'http://localhost:8100',  # The base url of the running ionic application.
}

pagination = {
    "example" : 10 # Limits returned rows of API
}

bearer_tokens = {
    "casting_assistant" : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJERTFSVGM0TVRrek9VWTJOalJGTVRoR016RTRRamRGUWpKRFJUaEJRa0l3UVRZeU1qTkNOQSJ9.eyJpc3MiOiJodHRwczovL2ZzbmRzLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZTgwYzgzMjVkZTFhMzBjNWVjZjNkOTciLCJhdWQiOiJDYXN0aW5nIiwiaWF0IjoxNTg5MjE3Mzg1LCJleHAiOjE1ODkzMDM3ODUsImF6cCI6InJlSXE3dGViYzkxN1pTUVpUbWlLY0hUYlk0SThPVE1mIiwic2NvcGUiOiIiLCJwZXJtaXNzaW9ucyI6WyJHRVQ6YWN0b3JzIiwiR0VUOm1vdmllcyJdfQ.Pr664W7bg-paoUnYvS_U5BYJZuyCu8KDkMAgtRTi2ch85T2PL7qnuM8jQbcyfQ2Ax8Fe4o_TOzHW2YEHo30-59DeQOH06y28w-qR01w1yB1qCS1BYr_kl4FMTUMnXrMFNuoRlA6nsRmif0CPk6phnA8ic1LegkLLLz0-DMdN8Y7AcjRRpWKZeYF8qx_Yr9PzWXf7r5kmAH-XFqYfVLVFNqvivSq1NTHgIf58NRJrc7rUQwN0f2L4xCI4qZybRAKqPIzSc_fPRlF_UPuyAQoirfzBNnHSAvkWB-H0MzI9YCh5RRHSWgtST_fuXKMtp1cLJc4wazme2S8e6FXjEOW2QA",
    "executive_producer" : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJERTFSVGM0TVRrek9VWTJOalJGTVRoR016RTRRamRGUWpKRFJUaEJRa0l3UVRZeU1qTkNOQSJ9.eyJpc3MiOiJodHRwczovL2ZzbmRzLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZWFlZDVlMGVhZjg1MTBiZTdlYTQ2M2UiLCJhdWQiOiJDYXN0aW5nIiwiaWF0IjoxNTg5MjE3MjU1LCJleHAiOjE1ODkzMDM2NTUsImF6cCI6InJlSXE3dGViYzkxN1pTUVpUbWlLY0hUYlk0SThPVE1mIiwic2NvcGUiOiIiLCJwZXJtaXNzaW9ucyI6WyJERUxFVEU6YWN0b3JzIiwiREVMRVRFOm1vdmllcyIsIkdFVDphY3RvcnMiLCJHRVQ6bW92aWVzIiwiUEFUQ0g6YWN0b3JzIiwiUEFUQ0g6bW92aWVzIiwiUE9TVDphY3RvcnMiLCJQT1NUOm1vdmllcyJdfQ.fI45bTOBFt2kf9j5Azr_YC-1G6zSQLAgdztiJxH0ecgZNjOXbH-O9nQupQ9veySWZpYMymOMzSXOTmDNcBB67VxYSrSPBW9LmyinmOo1pHpRF-5MolBLxWaMsDgcgENemN5GCAX5UC1HkWEK6wdof2LeXTDztxHegnh3lKVa6DZ9XaHM-5ZtA0r-sFIPuB04AK4zJIxOShuiSQiqBKiuEbC_Y-6m3Mo872wGMZNgfJqw48N2GXtS3EvxItLDrfJPG3tGnf2eMbHT60VFnsjeBvghLE1-ZYu4SIokT-rb167DGUNml0A_DWvtnyqfNvrOqpYQ77lBU0hRwBM1fvla1w",
    "casting_director" : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJERTFSVGM0TVRrek9VWTJOalJGTVRoR016RTRRamRGUWpKRFJUaEJRa0l3UVRZeU1qTkNOQSJ9.eyJpc3MiOiJodHRwczovL2ZzbmRzLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZTkwYTM5ZGY3NTk2MjBjMDhjN2JkYWYiLCJhdWQiOiJDYXN0aW5nIiwiaWF0IjoxNTg5MjE3NDY4LCJleHAiOjE1ODkzMDM4NjgsImF6cCI6InJlSXE3dGViYzkxN1pTUVpUbWlLY0hUYlk0SThPVE1mIiwic2NvcGUiOiIiLCJwZXJtaXNzaW9ucyI6WyJERUxFVEU6YWN0b3JzIiwiR0VUOmFjdG9ycyIsIkdFVDptb3ZpZXMiLCJQQVRDSDphY3RvcnMiLCJQQVRDSDptb3ZpZXMiLCJQT1NUOmFjdG9ycyJdfQ.QyOmBC0C2LjVbjgWf2IV3ZH-vWq1gQmMas8Dy1popTw2TR_dvjxyX25Ft5HJ7tdNhyo78dKGWZzbBI33kQZAFdL-pg07UKRM6OcE1XMmI0gjGjJ3cIbJ-zgS06bKrfH71b-dfHLPIMNKNXM6PR9xzUtU3EMw3gMk28Es8Tu28KkvCFKora9-qfM0dE6sYIAvqfqvrCSaXqCPg0O75eoQMs6Dk5hZXtcT4lzHfOaEpbMLkpLojb0ciZIK1OU1Y2Xwz-HI1AGhVGeQbhBXYKVwIJcFfc4TPYONNSlhNzziPAZIzeZgO9DmKkED7oB4PSL-0F8EZQOHfZ2_iUY9eF_cKA"
}